### ISSUE TITLE
Vector format

### ISSUE THREAD

**Issue by ryanholder** [danleech/simpleicons.org#51]
@danleech Have you had any thought on releasing the vector files so that a custom font cold be created ?

**Comment by dandv** [comment]
https://github.com/samcollins/css-social-buttons/ has many social icons in SVG format.

Some very good articles on SVG workflow, since you asked for that in the README:

* https://css-tricks.com/icon-fonts-vs-svg/
* https://css-tricks.com/svg-symbol-good-choice-icons/
* https://css-tricks.com/scale-svg/ (TL;DR: include the viewbox in the symbol definition)
